### ISSUE TITLE
Uniform code style

### ISSUE THREAD

**Issue by bartekpacia** [JBossOutreach/visiting-card-server#18]
Would be great if we had some rules for writing code. I think we should add `.eslintrc.json` so everybody who contribute to this project follow these rules.

It would be also easier for mentors to check tasks that are well-formatted and without `var`s 😄 

What do you think about it? I can do this.

**Comment by jatinkatyal13** [comment]
That would be great! 🎉  
Can you do this?

**Comment by bartekpacia** [comment]
Of course! 👍
